### ISSUE TITLE
Error when running npm run dev

### ISSUE THREAD

**Issue by jhrcek** [sporto/elm-tutorial-app#12]
Having finished the [chapter on webpack](http://www.elm-tutorial.org/en/04-starting/04-webpack-2.html) of your book I'm stuck with `npm run dev` command.
After cloning this repository and after `git checkout 02-webpack` and running the above command I'm getting this error:
![screenshot from 2016-06-16 21-47-31](https://cloud.githubusercontent.com/assets/2716069/16130965/104982ce-340c-11e6-815a-3e623833ce52.png)

Unfortunately I'm not particularly skilled with npm. Any ideas?
Your elm tutorial book is great, by the way :-)

**Comment by sporto** [comment]
Looks like the webpack config is not quite right, let me check my instructions

**Comment by sporto** [comment]
I think this is the version of Node, which version are you using?

**Comment by jhrcek** [comment]
Is this what you mean?

```
$ node -v
v0.10.42
$ npm -v
1.3.6
```

**Comment by jhrcek** [comment]
I reinstalled node to 4.4.5 and it's working fine. Thanks for the tip :-)
