### ISSUE TITLE
Error running npm run dev

### ISSUE THREAD

**Issue by sandust** [sporto/elm-tutorial-app#15]
> npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! elm-tutorial-app@1.0.0 dev: `webpack-dev-server --port 3000`
npm ERR! Exit status 3221226505
npm ERR!
npm ERR! Failed at the elm-tutorial-app@1.0.0 dev script 'webpack-dev-server --port 3000'.

full log:[npm-debug.zip](https://github.com/sporto/elm-tutorial-app/files/583496/npm-debug.zip)

I followed the tutorial to the point of [Webpack2](https://www.elm-tutorial.org/en/04-starting/04-webpack-2.html) and get this error.

I also tried pulling the project directly from git and I get the same error. build and watch command works fine.

As you can see in the error above I'm running the latest node and npm versions.

Any ideas?

**Comment by sporto** [comment]
Haven't tried in Node 7 yet, will have a look

**Comment by sporto** [comment]
I just tried in node 7.1 and npm 3.10.9, didn't hit any issues yet

**Comment by sandust** [comment]
I just tried reinstalling node 7.1 and still didn't work. I changed to the LTS version (6.9.1) and then it worked.
I'm using the x64 version and I'm in Windows 10.

I'll just keep using the LTS version for now, so is not an issue anymore for me. You can close the issue if you think is an isolated case.
