### ISSUE TITLE
0.18 Upgrade

### ISSUE THREAD

**Issue by BryanJBryce** [sporto/elm-tutorial-app#16]
Any plans to upgrade to 0.18? The major differences I've found so far are the new Http libraries and new Github repo location.

**Comment by sporto** [comment]
Yes, I am in the process of doing the upgrade.

**Comment by lromanov** [comment]
@sporto Please have a look at my pull request #18 on the subject.

**Comment by sporto** [comment]
Upgrade is done, thanks @lromanov   for the help. Next I need to update the actual tutorial.
