### ISSUE TITLE
Error with inline comments: error

### ISSUE THREAD

**Issue by niksmac** [sporto/elm-tutorial-app#17]
Here https://www.elm-tutorial.org/en/02-elm-arch/cover.html 

> Error with inline comments: error 
![screen shot 2016-11-17 at 1 44 57 pm](https://cloud.githubusercontent.com/assets/124470/20381123/0e3e17ae-accc-11e6-8e1b-8052fe9f9bb3.png)

**Comment by sporto** [comment]
Don't know what this is, must have been a gitbook issue, it looks fine now. Please re open if it is still happening.
