### ISSUE TITLE
Compile error while decoding id

### ISSUE THREAD

**Issue by ffos** [sporto/elm-tutorial-app#20]
As I was going through the app before the commit on the git-book (https://github.com/sporto/elm-tutorial/commit/c493d5000c6d886f98fd4fce0723eb8af5905664) was merged, I ran into this error:

Elm Version: `0.18.0`
Error:
```
ERROR in ./src/Main.elm
Module build failed: Error: Compiler process exited with error Compilation failed
-- TYPE MISMATCH ------------------------------------ ./src/Players/Commands.elm

The 2nd argument to function `map3` is causing a mismatch.

57|         Decode.map3 Player
58|>            (field "id" Decode.string)
59|             (field "name" Decode.string)
60|             (field "level" Decode.int)

Function `map3` is expecting the 2nd argument to be:

    Decode.Decoder PlayerId

But it is:

    Decode.Decoder String
```

`db.json` :
```
{
  "players": [
    {
      "id": "2",
      ...
    ...
}
```

`Players/Models.elm`:
```
type alias PlayerId =
    Int
```

Instead of changing `PlayerId` value to string as done in the git-book commit, it will be a good demonstration to convert string to int while decoding.

**Comment by sporto** [comment]
Not quite what you are asking but:

The id needs to be a string in the db json file too. I tried using integers as before but the `json-server` node module wouldn't save the changes when doing a patch request. It would insist in changing the ids to strings. Once I changed the ids to strings in that file everything started working again. So this is the reason I changed from ints to strings.

https://github.com/typicode/json-server/issues/273

As to demonstrate the conversion from string to int. I prefer not to do that, there is so many things that can be added by I want to keep the tutorial to the minimum necessary.

**Comment by ffos** [comment]
I think it's a common case to massage data coming from the server. In this case, it's simple enough for a demonstration, where in a single method you see straight forward decoding as well as chained decoding. Being new to elm, it was a major struggling point for myself.

Can u look at the pull-request: https://github.com/sporto/elm-tutorial-app/pull/21 and see if you still more-or-less adjusts into your simplicity goal, for the benefit it provides to handle such a common case.

If you are open to it, I will create another pull request to make corresponding adjustments on the git-book
