### ISSUE TITLE
Possible bug in View.elm

### ISSUE THREAD

**Issue by sashaafm** [sporto/elm-tutorial-app#25]
Hello, I'm following your tutorial and in the Routing section there's this `playerEditPage : Model -> PlayerId -> Html Msg` function which looks like this:

```
playerEditPage : Model -> PlayerId -> Html Msg
playerEditPage model playerId =
    let
        maybePlayer =
            model.players
                |> List.filter (\player -> player.id == playerId)
                |> List.head
    in
        case maybePlayer of
            Just player ->
                Html.map PlayersMsg (Players.Edit.view player)

            Nothing ->
                notFoundView
```

However, I'm getting this error upon running `nf start`:

```
Module build failed: Error: Compiler process exited with error Compilation failed -- SYNTAX PROBLEM ---------------------------------------------- ./src/View.elm                                                                                                               
Arrows are reserved for cases and anonymous functions. Maybe you want > or >= instead?
43|             Nothing ->     
```

I'm on Ubuntu 16.04 with Elm 0.18. I've even copy pasted the original source code from here and it gives the same error. The code looks absolutely fine to me, it's a `case of` like any other and the signature of `List.head` seems to be `Just a | Nothing` like in the provided cases.

**Comment by sporto** [comment]
Hi, can you double check your indentation. If the indendation is not quite right e.g. (3 spaces instead of 4) you can get errors like this. Let me know

**Comment by sporto** [comment]
Closing as inactive
