### ISSUE TITLE
Congrats

### ISSUE THREAD

**Issue by rwoodnz** [sporto/elm-tutorial-app#26]
Not an issue, rather a big congrats. An elm tutorial I actually got through without it all falling to pieces.
As general feedback I'd say it got quite complex quite quick, with the union types, pattern matching and the advanced navigation. 
I'm still struggling with how functions and parameters are passed around. Often I miss in the syntax whether two words next to each other are two parameters, a function calling a parameter, a parameter being passed as another function calling a parameter, or something to do with a type constructor or what - but if anything that's an elm problem not yours.
Thank you for managing to explain the elm architecture concisely and understandably with the diagrams (although I'll need repeat exposure until it sinks in). Some people don't take into account we haven't all done functional reactive programming before. Navigation explanation on top of that was also a bonus.
Overall perhaps a bit of repetition on the way through and some variation on showing other ways things might be done would aid learning and embedding concepts in our minds even if at the expense of greater length.
If you can recommend other tutorials and places to go online for beginner discussion please do add them at the end as well.
Cheers

**Comment by sporto** [comment]
@rwoodnz thanks very much for the feedback. It is always very useful. I'm glad you find the tutorial useful.
