### ISSUE TITLE
Proposal: Avoid foreman as global dependency

### ISSUE THREAD

**Issue by leskeg-zz** [sporto/elm-tutorial-app#27]
It would be more convenient to add foreman as a normal dependency and call it using npm start:

package.json
```javascript
"dependencies": {
  ...
  "foreman": "^2.0.0"
  ...
},
...
"scripts": {
  "start": "nf start"
  ...
}```

**Comment by sporto** [comment]
Agree, will do.

**Comment by leskeg-zz** [comment]
Also `webpack-dev-middleware` is not used, it could be removed

**Comment by sporto** [comment]
Done

**Comment by leskeg-zz** [comment]
Don't forget update `readme.md` according to the change
