### ISSUE TITLE
Q: Difference between Eng v1 and Eng v2?

### ISSUE THREAD

**Issue by eboCode** [sporto/elm-tutorial-app#34]
Opening the tutorial pages at elm-tutorial.org, the site asks you to 'Choose a language.' What's the difference there between choosing 'English - v2' and 'English - v1'? In other words, how is v2 updated, if at all?

**Comment by sporto** [comment]
When v1 was created using the nested update-view-model pattern was common in Elm. This tutorial built on this pattern. 

But then the community started recommending to avoid this pattern when possible. Doing flatter models and updates. V2 follows the latest community recommendations better, by not using nested update-view-model.
