### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by chasm** [sporto/elm-tutorial-app#6]
A suggestion for how to improve this tutorial.

Each time you choose to include a dependency that is not absolutely necessary, you limit your audience. You've made several choices here that hurt. Do you really need StartApp? Should everyone who makes an Elm SPA use BassCSS and Webpack? These are not necessary when creating an Elm SPA, which is ostensibly what this tutorial is all about. By including them you confuse the issue. This is no longer the Elm SPA tutorial, it's the Elm SPA-Webpack-BassCSS-StartApp tutorial. Now everyone who _doesn't_ want to use those dependencies has to do the mental work to pull them back out again.

There is no problem with teaching people how to use StartApp, BassCSS, or Webpack, but there is a better way: Make the base tutorial as simple as possible. Focus on the task at hand: setting up an SPA and organizing your Elm code into files and modules. Explain your reasoning.

THEN, in a "startapp" branch, show how to use StartApp as a shortcut. In another branch (from the _master_ branch, _not_ the startapp branch) show how to include BassCSS. In yet another, show how to use Webpack with Elm. Now you haven't turned a significant portion of your audience into second-class citizens. Better still, you can always add a gulp branch or a JSPM brach or whatever else later if you want to provide more options (or maybe you change the way you do things).

```
base tutorial (master branch)
|- with startapp branch
|- with webpack branch
|- with basscss branch
|- etc.
```

You may always build your own Elm apps with StartApp, BassCSS, and Webpack, but your readers will thank you if you don't force those choices on them.

**Comment by sporto** [comment]
Appreciate the feedback thanks. 

I added Webpack just so I could add external css. Not trying to be prescriptive but I had to choose something and webpack seems like a popular choice. I'm willing to mention some alternatives in the relevant chapters. I think I can work in the language so it is clear that these are just some available options.

**Comment by chasm** [comment]
Thanks! I'm working through the tutorial now. Looks very good.

**Comment by klazuka** [comment]
I think the tutorial is great as-is. Part of what I like so much about this tutorial vs the standard Elm architecture tutorial is that it is far more real-world-y. The include of things like webpack, BassCSS and the Hop router contribute to that real-world feeling. And as a bonus, things like BassCSS kept the focus on the code rather than cluttering things up with a lot of CSS rules.

**Comment by sporto** [comment]
I'm closing this issue as I don't have a real action to do (already mentioned some alternatives in the relevant chapters). Please feel free to keep posting suggestions.
