### ISSUE TITLE
Uncaught SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by brobrts** [sporto/elm-tutorial-app#9]
When I run  -npm run dev-  from the tutorial just after configuring the project with webpack, I get this 
error in the console: Uncaught SyntaxError: Unexpected identifier

it points to this in app.js
/***/ function(module, exports) {

```
module Main (..) where  <<<<<<<<<<<

import Html exposing (..)
//...
```

as you would expect, the Loading... message is displayed on the screen since app.js can't load.

The project builds fine with - npm run build-
I made sure to check the versions are what was mentioned in the tutorial, and am plain stumped as to what is causing this.  

billyr

The terminal gives no indication of anything wrong. ...bundle valid.

billyr

**Comment by brobrts** [comment]
I'm getting the same error with the example project from the loader repo and one that uses the loader in another project.  It's clearly not anything to do with this repo.

Still, please let me know if others have this same experience - all builds fine and chokes on the import in the generated js file when loading.

**Comment by brobrts** [comment]
having a parent directory named elm-stuff was conflicting with the one of the same name that elm uses.
this solved the problem.

**Comment by sporto** [comment]
Great, good to hear is fixed
